'''initialize'''
from .ski import SkiGame
from .maze import MazeGame
from .gobang import GobangGame
from .tetris import TetrisGame
from .pacman import PacmanGame
from .gemgem import GemGemGame
from .tankwar import TankWarGame
from .sokoban import SokobanGame
from .pingpong import PingpongGame
from .trexrush import TRexRushGame
from .bomberman import BomberManGame
from .whacamole import WhacAMoleGame
from .catchcoins import CatchCoinsGame
from .flappybird import FlappyBirdGame
from .angrybirds import AngryBirdsGame
from .magictower import MagicTowerGame
from .aircraftwar import AircraftWarGame
from .bunnybadger import BunnyBadgerGame
from .minesweeper import MineSweeperGame
from .greedysnake import GreedySnakeGame
from .puzzlepieces import PuzzlePiecesGame
from .towerdefense import TowerDefenseGame
from .alieninvasion import AlienInvasionGame
from .breakoutclone import BreakoutcloneGame
from .bloodfootball import BloodFootballGame
from .twentyfourpoint import TwentyfourPointGame
from .flipcardbymemory import FlipCardByMemoryGame
from .twozerofoureight import TwoZeroFourEightGame
from .voicecontrolpikachu import VoiceControlPikachuGame