from modules.GameLevel import GameLevel
from modules.interfaces.gameEndIterface import gameEndIterface
from modules.interfaces.gameStartInterface import gameStartInterface
from modules.interfaces.switchLevelIterface import switchLevelIterface