'''initialize'''
from .ski import SkiGame
from .maze import MazeGame
from .tetris import TetrisGame
from .pacman import PacmanGame
from .gemgem import GemGemGame
from .tankwar import TankWarGame
from .sokoban import SokobanGame
from .pingpong import PingpongGame
from .trexrush import TRexRushGame
from .bomberman import BomberManGame
from .catchcoins import CatchCoinsGame
from .flappybird import FlappyBirdGame
from .aircraftwar import AircraftWarGame
from .bunnybadger import BunnyBadgerGame
from .puzzlepieces import PuzzlePiecesGame
from .towerdefense import TowerDefenseGame
from .alieninvasion import AlienInvasionGame
from .breakoutclone import BreakoutcloneGame
from .twentyfourpoint import TwentyfourPointGame
from .voicecontrolpikachu import VoiceControlPikachuGame