'''title'''
__title__ = 'cpgames'
'''description'''
__description__ = 'Games: Create interesting games in pure python'
'''url'''
__url__ = 'https://github.com/CharlesPikachu/Games'
'''version'''
__version__ = '0.1.2'
'''author'''
__author__ = 'Zhenchao Jin'
'''email'''
__email__ = 'charlesblwx@gmail.com'
'''license'''
__license__ = 'Apache License 2.0'
'''copyright'''
__copyright__ = 'Copyright 2021-2022 Zhenchao Jin'