'''title'''
__title__ = 'cpgames'
'''description'''
__description__ = 'Games: Create interesting games by pure python'
'''url'''
__url__ = 'https://github.com/CharlesPikachu/Games'
'''version'''
__version__ = '0.1.1'
'''author'''
__author__ = 'Zhenchao Jin'
'''email'''
__email__ = 'charlesblwx@gmail.com'
'''license'''
__license__ = 'MIT License'
'''copyright'''
__copyright__ = 'Copyright 2021 Zhenchao Jin'